import turtle
board = turtle.Turtle()
board.up()
board.goto(-120, 125)
board.speed(100000)
wn = turtle.Screen()
def drawBoard(pen):
    # pen.up()
    # pen.goto(-120,125)
    # pen.down()
    # pen.forward(240)
    # pen.right(90)
    # pen.forward(250)
    # pen.right(90)
    # pen.forward(240)
    # pen.right(90)
    # pen.forward(250)
    # pen.right(90)
    # pen.up()
    drawStudy(pen)
    drawHall(pen)
    drawLounge(pen)
    drawLibrary(pen)
    drawCellar(pen)
    drawDiningroom(pen)
    drawBilliardRoom(pen)
    drawConservatory(pen)
    drawBallroom(pen)
    drawKitchen(pen)
    floor = getFloorTiles()
    drawFloorTiles(pen, floor)


def drawStudy(board):
    board.up()
    board.goto(-120,125)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(60)
    board.right(90)
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(30)
    board.right(90)
    board.forward(70)
    board.right(90)
    board.forward(40)
    board.right(90)
    board.end_fill()
    board.up()


def getFloorTiles():
    floorTiles = []
    import csv
    with open('C:/Users/Ty/Documents/vsc/ClueLocalGit/csv/board.csv', 'r') as userFile:
        userFileReader = csv.reader(userFile)
        for row in userFileReader:
            print(row)
            currentX = -135
            for cell in row:
                currentX += 10
                if cell == 'Floor':
                    floorTiles.append([int(currentX), int(row[0])])
    print(floorTiles)
    return floorTiles

def drawFloorTiles(board, floorTiles):
    for tile in floorTiles:
        board.up()
        board.goto(tile[0], tile[1])
        board.color("black", "orange")
        board.left(90)
        board.forward(5)
        board.right(90)
        board.forward(-5)
        board.down()
        board.begin_fill()
        for i in range(4):
            board.forward(10)
            board.right(90)
        board.end_fill()
        
        board.up()
    
def drawHall(board):
    board.up()
    board.goto(-30, 125)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(60)
    board.right(90)
    board.forward(70)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.forward(70)
    board.right(90)
    board.end_fill()
    board.up()

def drawLounge(board):
    board.up()
    board.goto(50,115)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.forward(70)
    board.right(90)
    board.forward(50)
    board.right(90)
    board.end_fill()
    board.up()

def drawLibrary(board):
    board.up()
    board.goto(-120,55)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(50)
    board.right(90)
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(30)
    board.right(90)
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(50)
    board.right(90)
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(30)
    board.right(90)
    board.end_fill()
    board.up()

def drawCellar(board):
    board.up()
    board.goto(-30,45)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(50)
    board.right(90)
    board.forward(70)
    board.right(90)
    board.forward(50)
    board.right(90)
    board.forward(70)
    board.right(90)
    board.end_fill()
    board.up()

def drawDiningroom(board):
    board.up()
    board.goto(40,35)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(80)
    board.right(90)
    board.forward(70)
    board.right(90)
    board.forward(50)
    board.right(90)
    board.forward(10)
    board.left(90)
    board.forward(30)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.end_fill()
    board.up()

def drawBilliardRoom(board):
    board.up()
    board.goto(-120, 5)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(60)
    board.right(90)
    board.forward(50)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.forward(50)
    board.right(90)
    board.end_fill()
    board.up()

def drawConservatory(board):
    board.up()
    board.goto(-120,-75)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(40)
    board.right(90)
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(40)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.forward(40)
    board.right(90)
    board.end_fill()
    board.up()

def drawBallroom(board):
    board.up()
    board.goto(-40,-45)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(80)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.forward(20)
    board.left(90)
    board.forward(20)
    board.right(90)
    board.forward(40)
    board.right(90)
    board.forward(20)
    board.left(90)
    board.forward(20)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.end_fill()
    board.up()

def drawKitchen(board):
    board.up()
    board.goto(60,-55)
    board.down()
    board.color("black", "green")
    board.begin_fill()
    board.forward(50)
    board.right(90)
    board.forward(10)
    board.left(90)
    board.forward(10)
    board.right(90)
    board.forward(50)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.forward(60)
    board.right(90)
    board.end_fill()
    board.up()

drawBoard(board)
wn.exitonclick()
